/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoginDevelopment;

//import edu.ucue.tfc.Service.VideoService;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//import org.opencv.core.Core;

/**
 *
 * @author Paul
 */
public class Principal extends javax.swing.JFrame {
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    private void initComponents() {

        jpnlBackVideo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jmenubarVideo = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuitemNuevo = new javax.swing.JMenuItem();
        menuitemEliminar = new javax.swing.JMenuItem();
        menuitemListar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuitemDiagrama = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CVTrafficCounter");
        setLocationByPlatform(true);

        jLabel1.setFont(new java.awt.Font("TimesNewRoman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Conteo de Carros ");

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Perpendicularmente");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        //jLabel3.setText("bdsdg");
        jLabel3.setText("CVTrafficCounter .....");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jpnlBackVideo);
        jpnlBackVideo.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(jLabel2)))
                        .addGap(0, 209, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ucue/tfc/GUI/icons/video-player.png"))); // NOI18N
        jMenu1.setText("Video");

        menuitemNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ucue/tfc/GUI/icons/clapperboard.png"))); // NOI18N
        menuitemNuevo.setText("Nuevo Registro");
        menuitemNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(menuitemNuevo);

        menuitemEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ucue/tfc/GUI/icons/unchecked-1.png"))); // NOI18N
        menuitemEliminar.setText("Eliminar Registro");
        menuitemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemEliminarActionPerformed(evt);
            }
        });
        jMenu1.add(menuitemEliminar);

        menuitemListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ucue/tfc/GUI/icons/file-4.png"))); // NOI18N
        menuitemListar.setText("Listar Registros");
        menuitemListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemListarActionPerformed(evt);
            }
        });
        jMenu1.add(menuitemListar);

        jmenubarVideo.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ucue/tfc/GUI/icons/folder-5.png"))); // NOI18N
        jMenu2.setText("Datos");

        menuitemDiagrama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ucue/tfc/GUI/icons/statistics.png"))); // NOI18N
        menuitemDiagrama.setText("Diagrama de barras");
        menuitemDiagrama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemDiagramaActionPerformed(evt);
            }
        });
        jMenu2.add(menuitemDiagrama);

        jmenubarVideo.add(jMenu2);

        setJMenuBar(jmenubarVideo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlBackVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlBackVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold> 
     
  
  /*  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jmenubarVideo = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuitemNuevo = new javax.swing.JMenuItem();
        menuitemEliminar = new javax.swing.JMenuItem();
        menuitemListar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuitemDiagrama = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CVTrafficCounter");
        setLocationByPlatform(true);

        jLabel4.setText("jLabel4");

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("#1 Perpendicularmente");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel3.setText("CVTrafficCounter");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel2)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ucue/tfc/GUI/icons/video-player.png"))); // NOI18N
        jMenu1.setText("Video");

        menuitemNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ucue/tfc/GUI/icons/clapperboard.png"))); // NOI18N
        menuitemNuevo.setText("Nuevo Registro");
        menuitemNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(menuitemNuevo);

        menuitemEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ucue/tfc/GUI/icons/unchecked-1.png"))); // NOI18N
        menuitemEliminar.setText("Eliminar Registro");
        menuitemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemEliminarActionPerformed(evt);
            }
        });
        jMenu1.add(menuitemEliminar);

        menuitemListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ucue/tfc/GUI/icons/file-4.png"))); // NOI18N
        menuitemListar.setText("Listar Registros");
        menuitemListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemListarActionPerformed(evt);
            }
        });
        jMenu1.add(menuitemListar);

        jmenubarVideo.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ucue/tfc/GUI/icons/folder-5.png"))); // NOI18N
        jMenu2.setText("Datos");

        menuitemDiagrama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ucue/tfc/GUI/icons/statistics.png"))); // NOI18N
        menuitemDiagrama.setText("Diagrama de barras");
        menuitemDiagrama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemDiagramaActionPerformed(evt);
            }
        });
        jMenu2.add(menuitemDiagrama);

        jmenubarVideo.add(jMenu2);

        setJMenuBar(jmenubarVideo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
*/
    private void menuitemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemNuevoActionPerformed
/*        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        RegistroVideo video = new RegistroVideo();
        video.show();*/
    }//GEN-LAST:event_menuitemNuevoActionPerformed

    private void menuitemEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemEliminarActionPerformed
        // TODO add your handling code here:
     /*   if (!VideoService.getMapRegistros().isEmpty()) {
            BuscarRegistros eliminar = new BuscarRegistros();
            eliminar.show();
        } else {
            JOptionPane.showMessageDialog(rootPane, "No hay registros guardados!");
            return;
        }*/
        
    }//GEN-LAST:event_menuitemEliminarActionPerformed

    private void menuitemListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemListarActionPerformed
        // TODO add your handling code here:
      /*  if (!VideoService.getMapRegistros().isEmpty()) {
            ListaRegistros listaRegistros = new ListaRegistros();
            listaRegistros.setLista(VideoService.getRegistros());
            listaRegistros.show();
        } else {
            JOptionPane.showMessageDialog(rootPane, "No hay registros guardados!");
            return;
        }*/
    }//GEN-LAST:event_menuitemListarActionPerformed

    private void menuitemDiagramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemDiagramaActionPerformed
        // TODO add your handling code here:
      /*  if (!VideoService.getMapRegistros().isEmpty()) {
            GraficarRegistro grafico = new GraficarRegistro();
            grafico.show();
        } else {
            JOptionPane.showMessageDialog(rootPane, "No hay registros guardados!");
            return;
        }*/
    }//GEN-LAST:event_menuitemDiagramaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuBar jmenubarVideo;
    private javax.swing.JMenuItem menuitemDiagrama;
    private javax.swing.JMenuItem menuitemEliminar;
    private javax.swing.JMenuItem menuitemListar;
    private javax.swing.JMenuItem menuitemNuevo;
    // End of variables declaration//GEN-END:variables
}
